spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: Password123
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      #create-drop is for production since it will recreate your tables over again
      #update all it does is update your tables and it will not recreate 
      #validate will just validate that schema should be the same
      ddl-auto: create-drop
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081